In [77]:
import pandas as pd
import numpy as np

In [78]:
st1 = {'Stu_ID':list(range(100,116)),
      'Name':['Ankit','Shreya','Aakansha','Siddhi','Shubham','Rahul',
            'Vipin','Harsh','Yashika','Ritwik','Sharvil','Ritesh',
            'Saurav','Pankaj','Prashant','Ritu'],
    'Math_Score':[78,67,56,45,34,89,32,93,78,82,90,81,74,65,56,85],
     'Co_Curr_Score':[6.7,np.nan,7.0,9.0,8.1,3.8,2.3,5.1,6.3,7.5,np.nan,5.1,7.8,9.1,6.7,8.0],
    'Fee_Discount(%age)':[5,0,0,10,5,15,20,10,10,20,0,10,15,20,5,0],
     'Opted_Bus':[True,False,False,True,True,True,True,False,False,True,False,True,False,np.nan,True,True],
    'Personality_Score':[3.2,1.9,4.1,4.2,3.9,np.nan,3.5,2.4,4.4,3.6,4.0,3.2,3.6,4.4,4.0,3.8],
     'Fee':['P','R','P','P','P','P','P','P','R',np.nan,'P','R','P','P','P','P'],
    'CReg_No':['AJM-103','AJM-148','AJM-411',np.nan,'AJM-301','AJM-128','AJM-183',np.nan,
               'AJM-193',np.nan,'AJM-391','AJM-109','AJM-092','AJM-016','AJM-293','AJM-452']
     }

st2 = {'S_ID':list(range(100,116)),
      'City':['Mumbai','Delhi','Pune','Mumbai','Mumbai','Delhi','Lucknow',
            'Pune','Delhi','Kolkata','Pune','Pune','Kolkata','Delhi','Lucknow','Delhi'],
     'Languages_Known':[3,2,4,1,2,3,2,1,3,1,1,2,1,3,2,1],
     'Total_Followers':['543','234','0','340','589','750','1125',
                        '1731','264','891','0','647','0','2568','345','450'],
     'Active_On':['Facebook','IG','None','IG','IG','FB','Youtube','IG','Insta','youtube',
                  'None','Insta','None','IG','YT','FB'],
       'DOB':['1999-01-15','2003-10-22','2000-07-02','2002-10-15','2001-12-20',
             '1999-07-07','1998-01-28','2002-12-24','2003-03-14','1999-03-29',
             '2000-07-12','2002-07-17','1997-07-09','2004-12-30','2001-12-25','2002-11-18']
     }

# Fee:  'P' = Pending, 'R'= Recieved
# Opted Bus:  True - opted for bus, False - not opted for bus
# Active On:  FB(FaceBook),IG(Instagram),YT(YouTube),

#### Exercise
1) Create a dataframe df1 using st1 dictionary.<br>
2) Create a dataframe df2 using st2 dictionary.<br>
3) Join df1 and df2 using inner method in dataframe df <br>
4) Display the info for df<br>
5) Display all the sum of null values for each column in the dataframe df<br>
6) Handle the null values as following<br><pre>
    a) Replace null values in Co_Curr_Score with its Mean.
    b) Replace null values in Personality_Score with its Median.
    c) Replace null values in Fee with its Mode.
    d) Replace null values in Opted_Bus with its Mode.
    e) Drop the column CReg_No.
    </pre>
7) Display the statistical summary of the dataframe<br>
8) Display the data types of different columns in df.<br>
9) Change the following data types<br><pre>
    a) Total_Followers to int
    b) DOB to datetime</pre><br>
10) Create Year_Birth, Quarter_Birth and Month_Birth (month name) columns based on DOB<br>
11) Find student details of those students who have opted for Bus and have Math_Score >70<br>
12) Find student details of those students whose Fee is Pending and who are not active on social media.<br>
13) Find Name, DOB, City, Fee, Opted_Bus, Math_Score,Co_Curr_Score,Languages_Known for students who belong to Delhi, Pune or Mumbai and who know at least 2 languages.<br>
14) Find Name,DOB,City,Math_Score,Personality Score for students where students are not born in Mar, Oct or Nov or have Score at least 4.0 in Personality Score<br>
15) Find Name,DOB,City,Math_Score,Active_On for students where students have scored between 75 to 85 in Math_Score or students are active on FB or IG. <br>
16) Find City and Fee status wise mean of Math Score <br>
17) Find Mean of Math and Personality Score based on Social media activity<br>
18) Find Sum of Co_Curr_Score and Personality_Score based on Fee status and Qtr on Month<br>
19) Create a new column Age of students<br>
20) Clean the column Active_On such that all the social media platforms retain the same names


##### Visulaization Questions
1) Depict different city count on a bar chart and a line chart separately<br>
2) Depict quartile distribution of Personality Score<br>
3) Depict frequency distribution of Age<br>
4) For all those students with personality score>3.0 depict percentage distribution of Maths score obtained of all the students on a chart<br>
5) For all those students opted for Bus, find the Avg Co_Curr_Score<br>
6) Depict the Personality_Score vs Co_Curr_Score on a scatter plot<br>
7) Depict mean of Math score based on City on a bar and a line chart superimposed<br>
8) For all those students who fees is pending(P) or who have opted for bus, find mean of Personality Score and Co_Curr Score<br>

In [79]:
# Q1
df1 = pd.DataFrame(st1)
df1

,Stu_ID,Name,Math_Score,Co_Curr_Score,Fee_Discount(%age),Opted_Bus,Personality_Score,Fee,CReg_No
0,100,Ankit,78,6.7,5,True,3.2,P,AJM-103
1,101,Shreya,67,NaN,0,False,1.9,R,AJM-148
2,102,Aakansha,56,7.0,0,False,4.1,P,AJM-411
3,103,Siddhi,45,9.0,10,True,4.2,P,NaN
4,104,Shubham,34,8.1,5,True,3.9,P,AJM-301
5,105,Rahul,89,3.8,15,True,NaN,P,AJM-128
6,106,Vipin,32,2.3,20,True,3.5,P,AJM-183
7,107,Harsh,93,5.1,10,False,2.4,P,NaN
8,108,Yashika,78,6.3,10,False,4.4,R,AJM-193
9,109,Ritwik,82,7.5,20,True,3.6,NaN,NaN
10,110,Sharvil,90,NaN,0,False,4.0,P,AJM-391
11,111,Ritesh,81,5.1,10,True,3.2,R,AJM-109
12,112,Saurav,74,7.8,15,False,3.6,P,AJM-092
13,113,Pankaj,65,9.1,20,NaN,4.4,P,AJM-016
14,114,Prashant,56,6.7,5,True,4.0,P,AJM-293
15,115,Ritu,85,8.0,0,True,3.8,P,AJM-452

In [80]:
# Q2
df2 = pd.DataFrame(st2)
df2

    S_ID     City  Languages_Known Total_Followers Active_On         DOB
0    100   Mumbai                3             543  Facebook  1999-01-15
1    101    Delhi                2             234        IG  2003-10-22
2    102     Pune                4               0      None  2000-07-02
3    103   Mumbai                1             340        IG  2002-10-15
4    104   Mumbai                2             589        IG  2001-12-20
5    105    Delhi                3             750        FB  1999-07-07
6    106  Lucknow                2            1125   Youtube  1998-01-28
7    107     Pune                1            1731        IG  2002-12-24
8    108    Delhi                3             264     Insta  2003-03-14
9    109  Kolkata                1             891   youtube  1999-03-29
10   110     Pune                1               0      None  2000-07-12
11   111     Pune                2             647     Insta  2002-07-17
12   112  Kolkata                1               0      None  1997-07-09
13   113    Delhi                3            2568        IG  2004-12-30
14   114  Lucknow                2             345        YT  2001-12-25
15   115    Delhi                1             450        FB  2002-11-18

In [81]:
# Q3
df = pd.merge(df1,df2,left_on = "Stu_ID",right_on = "S_ID",how = "inner")
df

,Stu_ID,Name,Math_Score,Co_Curr_Score,Fee_Discount(%age),Opted_Bus,Personality_Score,Fee,CReg_No,S_ID,City,Languages_Known,Total_Followers,Active_On,DOB
0,100,Ankit,78,6.7,5,True,3.2,P,AJM-103,100,Mumbai,3,543,Facebook,1999-01-15
1,101,Shreya,67,NaN,0,False,1.9,R,AJM-148,101,Delhi,2,234,IG,2003-10-22
2,102,Aakansha,56,7.0,0,False,4.1,P,AJM-411,102,Pune,4,0,None,2000-07-02
3,103,Siddhi,45,9.0,10,True,4.2,P,NaN,103,Mumbai,1,340,IG,2002-10-15
4,104,Shubham,34,8.1,5,True,3.9,P,AJM-301,104,Mumbai,2,589,IG,2001-12-20
5,105,Rahul,89,3.8,15,True,NaN,P,AJM-128,105,Delhi,3,750,FB,1999-07-07
6,106,Vipin,32,2.3,20,True,3.5,P,AJM-183,106,Lucknow,2,1125,Youtube,1998-01-28
7,107,Harsh,93,5.1,10,False,2.4,P,NaN,107,Pune,1,1731,IG,2002-12-24
8,108,Yashika,78,6.3,10,False,4.4,R,AJM-193,108,Delhi,3,264,Insta,2003-03-14
9,109,Ritwik,82,7.5,20,True,3.6,NaN,NaN,109,Kolkata,1,891,youtube,1999-03-29
10,110,Sharvil,90,NaN,0,False,4.0,P,AJM-391,110,Pune,1,0,None,2000-07-12
11,111,Ritesh,81,5.1,10,True,3.2,R,AJM-109,111,Pune,2,647,Insta,2002-07-17
12,112,Saurav,74,7.8,15,False,3.6,P,AJM-092,112,Kolkata,1,0,None,1997-07-09
13,113,Pankaj,65,9.1,20,NaN,4.4,P,AJM-016,113,Delhi,3,2568,IG,2004-12-30
14,114,Prashant,56,6.7,5,True,4.0,P,AJM-293,114,Lucknow,2,345,YT,2001-12-25
15,115,Ritu,85,8.0,0,True,3.8,P,AJM-452,115,Delhi,1,450,FB,2002-11-18

In [82]:
# Q4
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Stu_ID              16 non-null     int64
 1   Name                16 non-null     object
 2   Math_Score          16 non-null     int64
 3   Co_Curr_Score       14 non-null     float64
 4   Fee_Discount(%age)  16 non-null     int64
 5   Opted_Bus           15 non-null     object
 6   Personality_Score   15 non-null     float64
 7   Fee                 15 non-null     object
 8   CReg_No             13 non-null     object
 9   S_ID                16 non-null     int64
 10  City                16 non-null     object
 11  Languages_Known     16 non-null     int64
 12  Total_Followers     16 non-null     object
 13  Active_On           16 non-null     object
 14  DOB                 16 non-null     object
dtypes: float64(2), int64(5), object(8)
memory usage: 2.0+ KB

In [83]:
# Q5
df.isnull().sum()

Stu_ID                0
Name                  0
Math_Score            0
Co_Curr_Score         2
Fee_Discount(%age)    0
Opted_Bus             1
Personality_Score     1
Fee                   1
CReg_No               3
S_ID                  0
City                  0
Languages_Known       0
Total_Followers       0
Active_On             0
DOB                   0
dtype: int64

In [84]:
# Q6
# a
df['Co_Curr_Score'] = df['Co_Curr_Score'].fillna(df['Co_Curr_Score'].mean())
# b
df['Personality_Score'] = df['Personality_Score'].fillna(df['Personality_Score'].mean(),inplace = True)

C:\Users\VICTUS\AppData\Local\Temp\ipykernel_20688\1159681081.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Personality_Score'] = df['Personality_Score'].fillna(df['Personality_Score'].mean(),inplace = True)

In [85]:
# c
df['Fee'] = df['Fee'].fillna(df['Fee'].mode())
df['Opted_Bus'] = df['Opted_Bus'].fillna(df['Opted_Bus'].mode())

In [86]:
# d
df.drop('CReg_No',axis=1,inplace=True)

In [87]:
# 7
df.describe()

,Stu_ID,Math_Score,Co_Curr_Score,Fee_Discount(%age),S_ID,Languages_Known
count,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000
mean,107.500000,69.062500,6.607143,9.062500,107.500000,2.000000
std,4.760952,19.495192,1.817861,7.352721,4.760952,0.966092
min,100.000000,32.000000,2.300000,0.000000,100.000000,1.000000
25%,103.750000,56.000000,6.000000,3.750000,103.750000,1.000000
50%,107.500000,76.000000,6.700000,10.000000,107.500000,2.000000
75%,111.250000,82.750000,7.850000,15.000000,111.250000,3.000000
max,115.000000,93.000000,9.100000,20.000000,115.000000,4.000000

In [88]:
# 8
df.dtypes

Stu_ID                  int64
Name                   object
Math_Score              int64
Co_Curr_Score         float64
Fee_Discount(%age)      int64
Opted_Bus              object
Personality_Score      object
Fee                    object
S_ID                    int64
City                   object
Languages_Known         int64
Total_Followers        object
Active_On              object
DOB                    object
dtype: object

In [89]:
# 9 
df['Total_Followers'] = pd.to_numeric(df['Total_Followers'])
df['DOB'] = pd.to_datetime(df['DOB'])

In [90]:
df.dtypes

Stu_ID                         int64
Name                          object
Math_Score                     int64
Co_Curr_Score                float64
Fee_Discount(%age)             int64
Opted_Bus                     object
Personality_Score             object
Fee                           object
S_ID                           int64
City                          object
Languages_Known                int64
Total_Followers                int64
Active_On                     object
DOB                   datetime64[ns]
dtype: object

In [91]:
# 10
# Create Year_Birth column
df['Year_Birth'] = df['DOB'].dt.year

# Create Quarter_Birth column
df['Quarter_Birth'] = df['DOB'].dt.quarter

# Create Month_Birth column (Month Name)
df['Month_Birth'] = df['DOB'].dt.month_name()

In [92]:
df.dtypes

Stu_ID                         int64
Name                          object
Math_Score                     int64
Co_Curr_Score                float64
Fee_Discount(%age)             int64
Opted_Bus                     object
Personality_Score             object
Fee                           object
S_ID                           int64
City                          object
Languages_Known                int64
Total_Followers                int64
Active_On                     object
DOB                   datetime64[ns]
Year_Birth                     int32
Quarter_Birth                  int32
Month_Birth                   object
dtype: object

In [93]:
# 11
df[(df['Opted_Bus']) &(df['Math_Score']>70) ]

,Stu_ID,Name,Math_Score,Co_Curr_Score,Fee_Discount(%age),Opted_Bus,Personality_Score,Fee,S_ID,City,Languages_Known,Total_Followers,Active_On,DOB,Year_Birth,Quarter_Birth,Month_Birth
0,100,Ankit,78,6.7,5,True,None,P,100,Mumbai,3,543,Facebook,1999-01-15,1999,1,January
5,105,Rahul,89,3.8,15,True,None,P,105,Delhi,3,750,FB,1999-07-07,1999,3,July
9,109,Ritwik,82,7.5,20,True,None,NaN,109,Kolkata,1,891,youtube,1999-03-29,1999,1,March
11,111,Ritesh,81,5.1,10,True,None,R,111,Pune,2,647,Insta,2002-07-17,2002,3,July
15,115,Ritu,85,8.0,0,True,None,P,115,Delhi,1,450,FB,2002-11-18,2002,4,November

In [99]:
df['Active_On'].value_counts()

Active_On
IG          5
None        3
FB          2
Insta       2
Facebook    1
Youtube     1
youtube     1
YT          1
Name: count, dtype: int64

In [42]:
# 12
df[(df['Fee'] == 'P') & (df['Active_On']!='None')]

,Stu_ID,Name,Math_Score,Co_Curr_Score,Fee_Discount(%age),Opted_Bus,Personality_Score,Fee,S_ID,City,Languages_Known,Total_Followers,Active_On,DOB,Year_Birth,Quarter_Birth,Month_Birth
0,100,Ankit,78,6.7,5,True,None,P,100,Mumbai,3,543,Facebook,1999-01-15,1999,1,January
3,103,Siddhi,45,9.0,10,True,None,P,103,Mumbai,1,340,IG,2002-10-15,2002,4,October
4,104,Shubham,34,8.1,5,True,None,P,104,Mumbai,2,589,IG,2001-12-20,2001,4,December
5,105,Rahul,89,3.8,15,True,None,P,105,Delhi,3,750,FB,1999-07-07,1999,3,July
6,106,Vipin,32,2.3,20,True,None,P,106,Lucknow,2,1125,Youtube,1998-01-28,1998,1,January
7,107,Harsh,93,5.1,10,False,None,P,107,Pune,1,1731,IG,2002-12-24,2002,4,December
13,113,Pankaj,65,9.1,20,NaN,None,P,113,Delhi,3,2568,IG,2004-12-30,2004,4,December
14,114,Prashant,56,6.7,5,True,None,P,114,Lucknow,2,345,YT,2001-12-25,2001,4,December
15,115,Ritu,85,8.0,0,True,None,P,115,Delhi,1,450,FB,2002-11-18,2002,4,November

In [48]:
# 13
df.loc[
    (df['City'] == 'Delhi') & (df['Languages_Known'] >= 2),
    ['Name', 'DOB', 'City', 'Fee', 'Opted_Bus', 'Math_Score', 'Co_Curr_Score', 'Languages_Known']
]

,Name,DOB,City,Fee,Opted_Bus,Math_Score,Co_Curr_Score,Languages_Known
1,Shreya,2003-10-22,Delhi,R,False,67,6.607143,2
5,Rahul,1999-07-07,Delhi,P,True,89,3.800000,3
8,Yashika,2003-03-14,Delhi,R,False,78,6.300000,3
13,Pankaj,2004-12-30,Delhi,P,NaN,65,9.100000,3

In [52]:
# 15 Find Name,DOB,City,Math_Score,Active_On for students where students have scored between 75 to 85 in Math_Score or students are active on FB or IG.
df.loc[
    (df['Math_Score'].between(75,85)) | ((df['Active_On'] == 'FB') | (df['Active_On'] == 'IG')),
    ['Name','DOB','City','Math_Score','Active_On']
]

       Name        DOB     City  Math_Score Active_On
0     Ankit 1999-01-15   Mumbai          78  Facebook
1    Shreya 2003-10-22    Delhi          67        IG
3    Siddhi 2002-10-15   Mumbai          45        IG
4   Shubham 2001-12-20   Mumbai          34        IG
5     Rahul 1999-07-07    Delhi          89        FB
7     Harsh 2002-12-24     Pune          93        IG
8   Yashika 2003-03-14    Delhi          78     Insta
9    Ritwik 1999-03-29  Kolkata          82   youtube
11   Ritesh 2002-07-17     Pune          81     Insta
13   Pankaj 2004-12-30    Delhi          65        IG
15     Ritu 2002-11-18    Delhi          85        FB

In [60]:
# 14 Find Name,DOB,City,Math_Score,Personality Score for students 
# where students are not born in Mar, Oct or Nov or have Score at least 4.0 in Personality Score
df.loc[
    (
        (df['Month_Birth'] != 'March') &
        (df['Month_Birth'] != 'October') &
        (df['Month_Birth'] != 'November')
    ) |
    (df['Personality_Score'] >= 4.0),
    ['Name', 'DOB', 'City', 'Math_Score', 'Personality_Score']
]

        Name        DOB     City  Math_Score Personality_Score
0      Ankit 1999-01-15   Mumbai          78              None
2   Aakansha 2000-07-02     Pune          56              None
4    Shubham 2001-12-20   Mumbai          34              None
5      Rahul 1999-07-07    Delhi          89              None
6      Vipin 1998-01-28  Lucknow          32              None
7      Harsh 2002-12-24     Pune          93              None
10   Sharvil 2000-07-12     Pune          90              None
11    Ritesh 2002-07-17     Pune          81              None
12    Saurav 1997-07-09  Kolkata          74              None
13    Pankaj 2004-12-30    Delhi          65              None
14  Prashant 2001-12-25  Lucknow          56              None

In [61]:
# 16
df.groupby(['City', 'Fee'])['Math_Score'].mean()

City     Fee
Delhi    P      79.666667
         R      72.500000
Kolkata  P      74.000000
Lucknow  P      44.000000
Mumbai   P      52.333333
Pune     P      79.666667
         R      81.000000
Name: Math_Score, dtype: float64

In [64]:
# 17 Find Mean of Math and Personality Score based on Social media activity
df.groupby(['Active_On'])[['Math_Score', 'Personality_Score']].mean()

           Math_Score Personality_Score
Active_On
FB          87.000000               NaN
Facebook    78.000000               NaN
IG          60.800000               NaN
Insta       79.500000               NaN
None        73.333333               NaN
YT          56.000000               NaN
Youtube     32.000000               NaN
youtube     82.000000               NaN

In [66]:
# 18
df.groupby(['Fee','Quarter_Birth'])[['Co_Curr_Score', 'Personality_Score']].sum()

                   Co_Curr_Score Personality_Score
Fee Quarter_Birth
P   1                   9.000000                 0
    3                  25.207143                 0
    4                  46.000000                 0
R   1                   6.300000                 0
    3                   5.100000                 0
    4                   6.607143                 0

In [67]:
# 19
from datetime import datetime

today = datetime.today()

df['Age'] = today.year - df['DOB'].dt.year

In [68]:
df['Age']

0     27
1     23
2     26
3     24
4     25
5     27
6     28
7     24
8     23
9     27
10    26
11    24
12    29
13    22
14    25
15    24
Name: Age, dtype: int32

In [75]:
# 20 
df['Active_On'] = df['Active_On'].replace({
    'fb': 'Facebook',
    'FB': 'Facebook',
    'facebook': 'Facebook',

    'ig': 'Instagram',
    'IG': 'Instagram',
    'insta': 'Instagram',
    'Insta': 'Instagram',
    'instagram': 'Instagram',

    'wa': 'WhatsApp',
    'WA': 'WhatsApp',
    'whatsapp': 'WhatsApp',

    'youtube': 'Youtube',
    'YT': 'Youtube'
})

In [100]:
df['Active_On'].value_counts()

Active_On
IG          5
None        3
FB          2
Insta       2
Facebook    1
Youtube     1
youtube     1
YT          1
Name: count, dtype: int64